export const postTrivia = [
    [
        'Wowee, a perfect score! Did you study or something?! Come back tomorrow to extend the streak!',
        'The best way to spread Christmas cheer is getting 5 out of 5 on Christmas trivia! Don\'t forget to come back tomorrow and do it again!',
        "You can be too old for a lot of things, but you're never too old to go 5 out of 5 on Christmas Trivia. Nice job!",
    ],
    [
        "4 out of 5 ain't bad, that's for sure. Come back tomorrow and go for the perfect score!",
        "You are officially on the nice list with that effort. Keep up the good work tomorrow!",
        "My heart is officially three sizes bigger after seeing that effort. Get yourself a cookie to celebrate!",
    ],
    [
        "3 out of 5 is not too shabby at all. You may have a little brushing up to do before going on Christmas Jeopardy though.",
        "Can't complain with better than 50%. Definitely puts you on the nice list, even if you're not on the first page!",
        "You left a couple out there today, but 3 out of 5 ain't bad. Study up tonight over a cup of cocoa and come back tomorrow gunning for more!",
    ],
    [
        "2 out of 5 is pretty good...in baseball. In trivia, though, it leaves a little something to be desired. Tomorrow will be up your alley, I'm sure of it!",
        "Work to do I'd say, though this was a tough one. Onwards and upwards tomorrow, just like Santa's reindeer!",
        "What's important is that you did your best. You've still earned a cookie in my books. Come back tomorrow and I'm sure you'll turn it around!",
    ],
    [
        "Keep the change ya filthy animal! Study hard tonight and you'll be just fine for tomorrow, I'm sure.",
        "Buzz, your girlfriend! WOOF! Look on the bright side, at least you got one! Better luck is on the way tomorrow!",
        "Tough one out there today. But you did your best. Can't ask for anything more than that. Better luck is on the way tomorrow!",
    ],
    [
        "You stink! You smell like beef and cheese. You don\'t smell like Santa! Study up and come back tomorrow to try again!",
        "Hate to say it, but you might be a cotton-headed ninnymuggins! Go make a nice cup of hot chocolate to turn things around.",
        "Well... There's nowhere to go but up, right? Brush it off with a cup of cocoa and a cookie and come back tomorrow ready to get back on the board!",
    ],
];

export const welcomeText = [
    "Lovely to see you again. Let's get this party started!",
    "Hope you are having a wonderful December day. Let's get to it, shall we?",
    "Had a cookie yet today? Better fuel up before you get started!",
    "No matter how different a Who may appear, he will always be welcomed with holiday cheer!",
    "Christmas Day will always be, just as long as we have we.",
    "Cheer up, dude. It's Christmas!",
    "Good tidings we bring to you and your kin. We wish you a merry Christmas, and a Happy New Year!",
    "What do you call an obnoxious reindeer?<br><br><em>Rude-olph</em>!",
    "What did the stamp say to the Christmas card?<br><br><em>Stick with me and we'll go places!</em>",
    "What do you call Santa's little helpers?<br><br><em>Subordinate clauses!</em>",
    "How do you know when Santa is near?<br><br><em>You can always sense his presents</em>",
    "What do you call a broke Santa?<br><br><em>Saint Nickel-less!</em>",
    "What is every parent's favourite Christmas Carol?<br><br><em>Silent Night!</em>",
    "How do sheep wish each other a happy holiday?<br><br><em>Merry Christmas to Ewe!</em>",
    "How does a snowman get in shape?<br><br><em>He waits for the weather to warm up!</em>",
    "What did one snowman say to the other snowman?<br><br><em>Do you smell carrots?</em>",
    "Why we're Rudolph's parents upset at his report card?<br><br><em>He went down in History!</em>",
    "What is Santa's biggest fear?<br><br><em>Claus-trophobia!</em>",
    "What happened to the theif who stole an advent calendar?<br><br><em>He got 24 days!</em>",
    "Why was the snowman looking through the carrots?<br><br><em>He was picking his nose!</em>",
    "Why do mummies like Christmas so much?<br><br><em>They love all the wrapping!</em>",
    "Why does Santa have three gardens?<br><br><em>So he can ho, ho, ho!</em>",
    "What did Adam say the night before Christmas?<br><br><em>It's Christmas, Eve!</em>",
    "Why does Santa go down the chimney?<br><br><em>Because it soots him!</em>",
    "How does Santa clean his bathroom?<br><br><em>He uses Comet!</em>",
    "Who is never hungry at Christmas?<br><br><em>The turkey. He's always stuffed!</em>",
]